apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diag

resources:
  # kustomize build https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/app-configs/httpbin/overlays/metallb > deploy.yaml
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/app-configs/httpbin/overlays/metallb
  - httpbin.yaml
  - namespace.yaml
  - receiver.yaml
