apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # kustomize build https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/metallb-operator/operator/overlays/stable > operator.yaml
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/metallb-operator/operator/overlays/stable
  - operator.yaml
