apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # kustomize build https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/web-terminal/operator/overlays/fast > operator.yaml
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/web-terminal/operator/overlays/fast
  - operator.yaml
  - web-terminal-tooling.yaml
