apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: github-demo
spec:
  href: 'https://github.com/codekow/lab-gitops'
  location: ApplicationMenu
  text: Lab - GitOps
  applicationMenu:
    section: Git Repos
    imageURL: /static/assets/public/imgs/logos/github.svg
