apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # kustomize build https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/openshift-pipelines-operator-rh/operator/overlays/latest > operator.yaml
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/openshift-pipelines-operator-rh/operator/overlays/latest
  - operator.yaml
