apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # kustomize build https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/console-config/overlays/default?ref=v0.20 > branding.yaml
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/console-config/overlays/default?ref=v0.20
  - branding.yaml
  - link-github.yaml
